[tool.poetry]
name = "estoque-loja-eletronico"
version = "0.1.0"
description = ""
authors = ["rubenfreita <rubensfreitas65@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
